[variables]
NODE_ENV = "production"

[phases.install]
cmds = ["corepack enable", "corepack prepare yarn@4.9.2 --activate", "yarn install --immutable"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start:prod" 