[variables]
NODE_ENV = "production"
NODE_VERSION = "22.12.0"

[phases.install]
cmds = ["corepack enable", "corepack prepare yarn@4.9.2 --activate", "yarn install"]

[phases.build]
cmds = ["npx nx build twenty-server"]

[start]
cmd = "node packages/twenty-server/dist/src/main" 