# Nixpacks configuration for Twenty Server
[variables]
NODE_ENV = "production"

# Force yarn usage instead of npm
[providers.node]
packageManager = "yarn"

# Custom install phase to use yarn with proper flags
[phases.setup]
cmds = ["corepack enable"]

[phases.install]
cmds = ["yarn install --immutable"]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn start:prod" 